apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 2  # You can adjust based on your need
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-frontend-image:latest  # Replace with your actual image
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_SERVER_URL
              value: "http://backend:8080/employees"
